### ISSUE TITLE
Problème avec les sites multi-lingues

### ISSUE THREAD

**Issue by Luc-Nematis** [quadra-informatique/Magento-Module-Atos#15]
Quadra_Atos_Model_Config::getMerchantCountry() récupère la config du path "general/country" au lieu, à mon avis, de "payment/account/merchant_country"

config.xml, pour le noeud "global/payment/atos/languages", le code pour l'Espagne est "sp" au lieu de "es" et pour Allemagne = ge au lieu de "de". Ces code ne sont pas ceux officiels (ISO 3166-1-alpha-2)

**Comment by mpasquin** [comment]
Bonjour,

Le champ "payment/account/merchant_country" fait son apparition dans la version 1.7 de magento. Comme le module est rétro-compatible jusqu'à la version 1.5. De ce fait, nous ne pouvons pas utiliser ce champ.

Il n'y a pas d'erreur dans la configuation des codes pays. Effectivement, ce ne sont pas les codes ISO mais ceux utiliser par l'API d'Atos. Si vous possédez la documentation du plugin sips, les différentes valeurs sont listées dans le dictionnaire de données.

Merci pour votre retour.

Cordialement.
